import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safe: { flex: 1 },
  content: {
    width: "100%",
    maxWidth: 760,
    alignSelf: "center",
    gap: 14,
    padding: 20,
    paddingBottom: 48,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    marginBottom: 8,
  },
  headerTitle: { flex: 1 },
  backText: { color: "#1f6f78", fontSize: 16, fontWeight: "600" },
  title: { fontSize: 24, fontWeight: "700" },
  subtitle: { fontSize: 13, marginTop: 2 },
  actionText: { color: "#1f6f78", fontSize: 14, fontWeight: "600" },
  sectionTitle: { fontSize: 16, fontWeight: "700" },
  driveRow: { gap: 8, paddingVertical: 2 },
  driveChip: {
    borderWidth: 1,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  driveText: { fontSize: 14, fontWeight: "600" },
  searchBox: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 12,
  },
  searchInput: { flex: 1, minHeight: 46, fontSize: 15 },
  breadcrumbs: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 5,
  },
  crumbPart: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    maxWidth: 180,
  },
  crumbSeparator: { fontSize: 17 },
  crumbText: { fontSize: 14, fontWeight: "600" },
  resultLabel: { fontSize: 13 },
  fileRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    minHeight: 64,
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  fileIcon: { color: "#1f6f78", fontSize: 20, width: 24, textAlign: "center" },
  fileInfo: { flex: 1, gap: 3 },
  fileName: { fontSize: 15, fontWeight: "600" },
  fileMeta: { fontSize: 12 },
  fileChevron: { fontSize: 22, paddingLeft: 8 },
  empty: { paddingVertical: 20, textAlign: "center" },
  primaryButton: {
    backgroundColor: "#1f6f78",
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 48,
    paddingHorizontal: 16,
    marginTop: 4,
  },
  primaryButtonText: { color: "#ffffff", fontWeight: "700", fontSize: 15 },
  secondaryButton: {
    borderColor: "#1f6f78",
    borderWidth: 1,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 42,
    paddingHorizontal: 14,
    marginTop: 8,
  },
  secondaryButtonText: { color: "#1f6f78", fontWeight: "600", fontSize: 14 },
  disabled: { opacity: 0.5 },
  detailCard: { borderWidth: 1, borderRadius: 14, padding: 16, gap: 9 },
  authCard: { borderWidth: 1, borderRadius: 14, padding: 16, gap: 10 },
  input: {
    minHeight: 46,
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 12,
    fontSize: 15,
  },
  detailTitle: { fontSize: 18, fontWeight: "700" },
  buttonRow: { gap: 4 },
  tagList: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  tagChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderWidth: 1,
    borderRadius: 18,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  tagInputRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  tagInput: { flex: 1 },
  tagAddButton: { marginTop: 0 },
  success: { color: "#176b4d", fontWeight: "600" },
  closeButton: { alignSelf: "flex-end", paddingTop: 5 },
  jobsCard: { borderWidth: 1, borderRadius: 14, padding: 14, gap: 10 },
  jobsHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  jobRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 6,
  },
  error: { color: "#b42318", fontSize: 14, lineHeight: 20 },
  errorAction: { color: "#b42318", fontSize: 14, fontWeight: "600" },
});
