import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safe: { flex: 1 },
  content: { padding: 16, paddingBottom: 48, gap: 12 },
  header: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 8,
  },
  headerText: { flex: 1 },
  title: { fontSize: 21, fontWeight: "700" },
  subtitle: { fontSize: 13, marginTop: 2 },
  action: { color: "#1f6f78", fontSize: 15, fontWeight: "600" },
  error: {
    color: "#b42318",
    backgroundColor: "#fef3f2",
    padding: 12,
    borderRadius: 10,
  },
  tabs: { gap: 8, paddingVertical: 3 },
  tab: {
    paddingHorizontal: 13,
    paddingVertical: 9,
    borderWidth: 1,
    borderRadius: 18,
  },
  tabText: { fontSize: 13, fontWeight: "600" },
  quickLinks: { flexDirection: "row", gap: 8 },
  card: { borderWidth: 1, borderRadius: 14, padding: 14, gap: 10 },
  sectionTitle: { fontSize: 16, fontWeight: "700" },
  input: {
    minHeight: 44,
    borderWidth: 1,
    borderRadius: 9,
    paddingHorizontal: 12,
    paddingVertical: 9,
    fontSize: 15,
  },
  primaryButton: {
    alignSelf: "flex-start",
    backgroundColor: "#1f6f78",
    borderRadius: 9,
    paddingHorizontal: 15,
    paddingVertical: 11,
  },
  primaryButtonText: { color: "#fff", fontWeight: "600" },
  secondaryButton: {
    alignSelf: "flex-start",
    borderWidth: 1,
    borderColor: "#cbd5e1",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  secondaryButtonText: { color: "#1f6f78", fontWeight: "600" },
  destructiveText: { color: "#b42318" },
  disabled: { opacity: 0.5 },
  row: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    justifyContent: "space-between",
    paddingVertical: 8,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  rowBody: { flex: 1 },
  rowTitle: { fontSize: 15, fontWeight: "600" },
  rowMeta: { fontSize: 12, lineHeight: 18 },
  rowText: { flex: 1, fontSize: 14 },
  buttonRow: { flexDirection: "row", gap: 8, flexWrap: "wrap" },
  accessGroup: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    paddingVertical: 7,
  },
  requestCard: { borderWidth: 1, borderRadius: 10, padding: 10, gap: 8 },
  switchRow: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  json: {
    borderWidth: 1,
    borderRadius: 8,
    padding: 10,
    fontFamily: "monospace",
    fontSize: 11,
    lineHeight: 15,
    overflow: "hidden",
  },
});
